Simplify nullptr comparisons where appropriate
Make the codebase consistent, we already have a lot of implicit pointer comparisons.

Exception: Stay explicit on return's, example:
  return _db != nullptr;

Signed-off-by: Michael Schuster <michael@schuster.ms>
(cherry picked from commit 456c1eadbea6d88bb0c0b29f39af4f354d88f88c)
Signed-off-by: Michael Schuster <michael@schuster.ms>