Fix warning with clang
/usr/include/features.h:330:4: error: _FORTIFY_SOURCE requires compiling
with optimization (-O) [-Werror,-W#warnings]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)