fix Windows build
`cl` didn't quite like it:

```
error C2445: result type of conditional expression is ambiguous: types 'QByteArray' and 'const char [1]' can be converted to multiple common types
```

just changing the `auto` to `QByteArray` results in the same compile error

Signed-off-by: Jyrki Gadinger <nilsding@nilsding.org>